version: 2
jobs:
  build:
    machine: true
    #  - image: autodeploy
    steps:
      - checkout
      - run: docker build --tag autodeploy . && docker run -d --name autodeploy -p 80:80 autodeploy
      - run: echo "A first hello"
